### ISSUE TITLE
Pass audio through to the screen

### ISSUE THREAD

**Issue by Azerio102** [r0tary/FPGA-Audio-Visualizer#8]
Changed tasks to:
- [x] Implement RAM design source and output test values on the screen - Completed on 12.05.2023.
- [x] Pass Audio to DFT - Completed on 22.05.2023.
- [x] Connect DFT module with Video and pass a sine wave - Completed on 21.05.2023.
- [x] Display DFT magnitudes of Audio on the screen - Completed on 27.05.2023.

**Comment by r0tary** [comment]
27.05.2023. - Changed issue title to "Pass Audio to the Screen"

**Comment by r0tary** [comment]
Issue Closed - Audio DFT magnitudes displayed on the screen - 27.05.2023.
